repos:
  # General purpose hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10240']  # set limit to 10MB

  # Spell checking
  - repo: https://github.com/crate-ci/typos
    rev: v1.36.2
    hooks:
      - id: typos
        exclude: "^.*(.unity|.shadergraph|.fbx|.meta|.gitignore)$"

  # Forbid binary files in the repository
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
